apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: pypython
  janus-idp.io/tekton: pypython
  backstage.io/kubernetes-id: pypython
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: pypython
resources:
- deployment.yaml
- route.yaml
- service.yaml
